name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        echo "sam is dummie"
        gcc -std=gnu99 fizzbuzz.c
        ./a.out | diff fizzbuzz.txt -
        python3 fizzbuzz.py | diff fizzbuzz.txt -
        node fizzbuzz.js | diff fizzbuzz.txt -
        bash fizzbuzz.sh | diff fizzbuzz.txt -

